### ISSUE TITLE
rpm build issues and release issues

### ISSUE THREAD

**Issue by Swash1972** [mobilinkd/tnc1-python-config#2]
So in trying to build from source (tnc1-python-config-1.0.1.tar.gz) I'd get the following.
`/usr/bin/env: ‘python2.7\r’: No such file or directory`
python2.7 is in /usr/bin not /usr/bin/env
It's also using python2.7 and not python 3.6 

So I try the release TncConfigApp-1.0.0-1.noarch.rpm
Running TncConfigApp.py results in the following.

```
Traceback (most recent call last):
  File "/usr/bin/TncConfigApp.py", line 12, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_TncConfigApp.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/TncConfigApp.py", line 12, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial'

```
So I run "pip3 install pyserial" and try again
```
Traceback (most recent call last):
  File "/usr/bin/TncConfigApp.py", line 14, in <module>
    from TncModel import TncModel
ModuleNotFoundError: No module named 'TncModel'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 145, in apport_excepthook
    os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o640), 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_TncConfigApp.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/TncConfigApp.py", line 14, in <module>
    from TncModel import TncModel
ModuleNotFoundError: No module named 'TncModel'

```
try to pip3 install tncmodel.
tncmodel does not exist on pip.... now what?
Is this using custom modules?

Operating System		: Linux Mint 19.2 Tina
Processor		: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
Memory		: 32878MB (6086MB used)
Video		: GeForce GTX 1070/PCIe/SSE2

**Comment by rriggs** [comment]
The README.md on the main page contains build instructions for Linux, Windows and OS X.  If it's not picking up the right version of Python for you, then you need to specify it when buiilding:

`python3 ./setup.py bdist_rpm` (or whatever package format you want bdist to produce).

For Linux, I use Fedora or CentOS.  If you are using a different Linux version, you will need to adapt the dependency list as appropriate.

On Fedora, the following just works:
```
[rob@emerald ~]$ cd /tmp
[rob@emerald tmp]$ git clone git@github.com:mobilinkd/tnc1-python-config.git
Cloning into 'tnc1-python-config'...
...
[rob@emerald tmp]$ cd tnc1-python-config/
[rob@emerald tnc1-python-config]$ python3 ./setup.py bdist_rpm
Warning: 'platforms' should be a list, got type 'tuple'
Warning: 'keywords' should be a list, got type 'tuple'
/usr/lib64/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'executables'
  warnings.warn(msg)
running bdist_rpm
running egg_info
creating TncConfigApp.egg-info
...
+ exit 0
moving build/bdist.linux-x86_64/rpm/SRPMS/TncConfigApp-1.0.2-1.src.rpm -> dist
moving build/bdist.linux-x86_64/rpm/RPMS/noarch/TncConfigApp-1.0.2-1.noarch.rpm -> dist
```

**Comment by Swash1972** [comment]
Well first I don't have permission to clone git@github.com:mobilinkd/tnc1-python-config.git
But I used git clone https://github.com/mobilinkd/tnc1-python-config.git to get the latest

python3 ./setup.py bdist_rpm worked to build an rpm. No errors.
Documentation is lacking in how to run the program, but I found TncConfigApp.py in /usr/local/bin/
I ran it and got the following.
```
Traceback (most recent call last):
  File "/usr/local/bin/TncConfigApp.py", line 717, in <module>
    app = TncConfigApp()
  File "/usr/local/bin/TncConfigApp.py", line 37, in __init__
    os.path.join(glade_location(), "glade/TncConfigApp.glade"))
GLib.Error: g-file-error-quark: Failed to open file “/usr/local/bin/glade/TncConfigApp.glade”: No such file or directory (4)
```
TncConfigApp.glade was not installed to /usr/local/bin/ but to /usr/local/share/TncConfigApp/glade/TncConfigApp.glade

**Comment by Swash1972** [comment]
After doing the above I made a symbolic link
`sudo ln -s /usr/local/share/TncConfigApp/glade /usr/local/bin/`
After that I was able to run TncConfigApp.py can connect to my tnc
Thanks for the input!
I would highly suggest adding a little more detail to the "linux install" section of the README.md
I'd be more than happy to write it up. I appreciate all the work on this project, and what little I can do to help is freely offered.

**Comment by rriggs** [comment]
It looks like when the app is not installed in /usr (e.g. /usr/local) then the glade_location() function needs to be updated to find it.   As is, it is able to run the app from either /usr/bin or the workspace.  I guess one way to do this is to refer to the glade directory using a relative path like $bindir/../share/TncConfigApp/glade/.  It will then need to deal with distros that link /bin and /usr/bin.

Another option is to use the Python build system to build a package appropriate for your distro and install the package.  It should install everything in the right place and the glade file should be found.

**Comment by calinb7** [comment]
In case anyone runs into the issue reported here. Martin posted the following to the groups.io group:

> 
>  You have the right config app from git hub : https://github.com/mobilinkd/tnc1-python-config
>  Forget the rpm. You need Python 3 and pyserial and gobject for Python 3 (it's in readme.md) installed.
>  Just cd into path to wherever you downloaded it/tnc1-python-config  and run with:- python3 ./TncConfigApp.py
>  There is no need to install. Works for me.
>  73's
> Martin M0MJU.
> 

I think I needlessly spent more time trying to implement the Linux instructions in the README.md that describe how to build and install TncConfigApp than I spent assembling my NucleoTNC PCB! The instructions in the README.md are completely inapplicable to Linux so the GitHub project should be updated to reflect the information here.

Even after removing all the Windoze CR (CR/LF >> LF for Linux) in the files and updating all the python requirements, there's still a bunch of cx_Freeze and .dll stuff in setup.py and probably other stuff that I tried to correct to build an RPM that I'm forgetting now) that will crash the setup script under Linux.

Had I been successful in producing a .rpm file, I would still have needed to deal with converting or processing the rpm file for installation on my Debian and Arch-based Linux systems (which is hardly a reasonable requirement for a product that purports to support GNU/Linux in general.

I am grateful to Martin's post for keeping me from wasting even more time trying to build TncConfigApp! for Linux.

From README.md:

> 
>     Linux Build
>     ===========
>     This was built/tested with Python 3.6, pyserial-3.1.1 and pygobject-3.28.3python3-3.6.6-1.fc28.x86_64python3-pyserial-3.1.1-6.fc28.noarchpython3-gobject-3.28.3-1.fc28.x86_64./setup.py bdist_rpm Will build an RPM that can be installed.

Cal (AD8Q)
